tmpl8/src/render.rs
`git pull --depth=1` doesn't actually do this, and causes a fetch failure if the current remote `HEAD` isn't directly connected to our `HEAD`.  It appears that there isn't a clean way to prune the repo after fetching, so for now, just let commits accumulate.
=> tmpl8: don't try to keep cached clones shallow

rust/release-checklist.md, rust/release-checklist.yaml
Only enable it in coreos-installer for now.
https://github.com/coreos/fedora-coreos-tracker/issues/1240
=> rust: support `cargo vendor-filterer`

tmpl8/src/main.rs, tmpl8/src/render.rs
When templates and their rendered output are stored in the same repo, it's useful to be able to render directly into the repo root, without having to construct a spurious parent directory to render into.
=> tmpl8: add an option to render a single repository

.github/workflows/sync.yml
If multiple PRs merge in quick succession, we don't want the sync jobs to race with each other.
=> workflows: serialize sync runs

go/release-checklist.md
Historically we've been noting key changes in the GitHub release but not in the release notes, which is confusing.  Do it in both places.
=> go/release-checklist: note signing key changes in `release-notes.md`

rust/release-checklist.md, rust/release-checklist.yaml
Update the release notes in a separate PR from the release itself, since `cargo release` creates a tag.  It'd be annoying to have to move the tag locally after addressing PR comments.
https://github.com/coreos/afterburn/pull/767
https://github.com/coreos/coreos-installer/pull/905
=> rust: add changelog doc to Afterburn and coreos-installer

Makefile, tmpl8/src/main.rs, tmpl8/src/render.rs
We've been diffing against the downstream main branch, which creates an incentive to merge upstream template PRs expeditiously to keep the diff clean.  However, it also adds noise to the downstream Git history.  It'd be better to let changes accumulate in a PR, and merge it just before starting a release.
Add tmpl8 command-line options allowing it to sync the cache (and thus generate the diff) from the downstream PR branch instead.  If that branch is missing, fall back to the downstream main branch as before.  This is implemented via a regex and replacement string for repo URLs and a single branch name for all repos, since that's all we actually need right now.
Hardcode arguments in the Makefile to match the values used by the GitHub workflow.
=> Diff against branch in pending PR

.github/workflows/check.yml, .github/workflows/sync.yml
Templates need to be mentioned in `config.yaml` to be applied.  Fail PR CI if we find unreferenced ones.
=> workflows: check PRs for unreferenced templates

config.yaml, release-notes/require-release-note.yaml, release-notes/require-release-note.yml
https://github.com/coreos/actions-lib/pull/3 adds a generic GitHub Action to check that PRs either update a specified file or set a label indicating that no update is needed.  Template an Actions workflow that invokes the new Action to ensure that PRs update release notes.
=> Add template GitHub Actions workflow to check for release note updates

release-notes/require-release-note.yml
GitHub can spawn multiple release note jobs at a time, e.g. if multiple labels are added to a PR.  https://github.com/coreos/actions-lib/pull/5 should avoid correctness issues, but the multiple runs are still redundant.  Terminate or cancel any previous runs when a new one is queued.
=> release-notes: serialize job runs within a PR

go/release-checklist.md, rust/release-checklist.md
`REDHAT.COM` tickets are no longer accepted by `rhpkg`.
=> Switch internal Kerberos realm to `IPA.REDHAT.COM`

rust/release-checklist.md
As of https://github.com/coreos/cargo-vendor-filterer/pull/29, cargo-vendor-filterer allows putting vendored crates in a top-level directory inside the tarball.  Drop our manual tar workaround and add a checklist item ensuring the release operator has the latest version of the tool.
=> rust: switch back to generating tarballs with cargo-vendor-filterer

config.yaml, container/container-rebuild.yaml, container/container-rebuild.yml, container/container.yaml, container/container.yml
Onboard our stock container-building workflow.  We don't add every container-building repo here, just the ones that already follow a common template.
Explicitly set the `arches` parameter even when we're using the `actions-lib/build-container` default.  Since we're templating the configs, we can be a bit more verbose, and the workflow files are clearer when we don't depend on a default from `actions-lib`.
Once we've done that, if there's a security issue in a container base image, we need to be able to rebuild the container and update the registry tag that users are using.  For repos without Git tags, there's just `latest`/`main` and we can update it by pushing a commit.  But for repos with a `release` tag aliased to a versioned tag built from a Git tag, we need a way to create a new …
=> Add GitHub workflow templates for building and pushing containers

container/container-rebuild.yml, container/container.yml
$ podman run --rm quay.io/coreos/butane:v0.16.0 --version
Butane v0.15.0-62-g0a3904d
It turns out that when `actions/checkout` is told to check out a tag, it checks out the correct commit, but replaces the tag with a lightweight tag that it invents out of whole cloth (!!), apparently to handle the case where the tag was moved before we fetched it (?).  The Ignition and Butane build scripts compute the version string with `git describe`, which ignores that lightweight tag, so we end up with a version string derived from the previous release rather than the one that we're explicitly building.
Re-fetch the tag, as recommended in the `actions/checkout` issue, to get the real tag back.
xref https://github.com/actions/checkout/issues/290
=> container: fix version strings in Ignition/Butane release containers

fcos/release-checklist.md
The FCOS release checklist step that points the developer to the roll out PR is missing the repository location. Add the repo location to the step to clarify where the PR will appear.
Fixing the accidental downstream edit from https://github.com/coreos/fedora-coreos-streams/pull/597
=> fcos/release-checklist.md: add repo location for the rollout PR

rust/release-checklist.md, rust/release-checklist.yaml
`find target/vendor -name '*.a' -delete` isn't safe, because at least rustix ships static archives even on Linux.  Switch everything to cargo-vendor-filterer.
Every affected repo has been updated; see https://github.com/coreos/repo-templates/pull/42#issuecomment-1246711208.
=> rust: always use cargo-vendor-filterer to make vendor tarballs

shellcheck/script.sh, shellcheck/script.yaml, shellcheck/workflow.yaml
Enable ShellCheck for Ignition
See: https://github.com/coreos/ignition/pull/1549
---
shellcheck/script.sh: Also ignore ./vendor dir
Useful for Go repos with a `./vendor` directory.
=> Enable ShellCheck for Ignition

config.yaml, shellcheck/script.yaml, shellcheck/workflow.yaml
config.yaml: Add coreos-installer-dracut repo
---
Enable ShellCheck for coreos-installer-dracut
See: https://github.com/coreos/coreos-installer-dracut/pull/11
---
Based on https://github.com/coreos/repo-templates/pull/72 to make rebases easier.
=> Enable ShellCheck for coreos-installer-dracut

fcos/release-checklist.md
add guidelines to remove ambiguity around release rollouts.
I wanted to make this step a bit more obvious. I feel like I tend to stump my toe on this.
=> release-checklist: add rollout guidelines

rust/release-checklist.md
When I created the PR: https://github.com/coreos/repo-templates/pull/94, I forgot about the rust package which could use this info as well.
=> rust/release-checklist: add link for RHCOS spec file

config.yaml, go/release-checklist.md
The package still exists, but I've dropped maintainership.  The FCOS docs [mention](https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/#_installing_via_macports) that the package is available in MacPorts, but I don't think it needs to be kept 100% current or maintained directly by the CoreOS WG. The package is [marked](https://github.com/macports/macports-ports/blob/60fcf499ab358aac11015a7d909544d4c5a2555f/sysutils/butane/Portfile#L9) `openmaintainer`, so anyone can submit an update PR when they want.
=> go/release-checklist: drop Butane MacPorts package

rust/release-checklist.md
Minor clarity improvement.  The Go checklist already does this.
=> rust: substitute current Fedora version

rust/release-checklist.md
We've had two cases of cargo-vendor-filterer creating incorrect tarballs:
https://github.com/coreos/cargo-vendor-filterer/issues/27
https://github.com/coreos/cargo-vendor-filterer/issues/71
With the current checklist flow, we don't notice until the upstream release is complete and we're doing a RHEL build with the vendored tarball, forcing us to make a second release with a fixed tarball. Catch this before release by generating a provisional vendor directory during the prep phase and running `cargo test` against it.
=> rust: test vendor tarball before releasing

shellcheck/workflow.yml
While we're fixing this in the Go and Rust workflows, let's fix it here too.
=> shellcheck: fix typo in workflow step name

tmpl8/src/cache.rs
When syncing a cached Git repo, we try to pull from our fork's PR branch when possible.  This lets us generate diffs that exclude any changes already merged upstream, PRed downstream, but not yet landed downstream.
However, when onboarding a new Git repo, our fork is created by `sync.yml` after the upstream onboarding PR is merged.  Thus, if the fork is missing, the cache needs to fall back to the downstream default branch so upstream PR CI can pass.  There's existing code to do that, but it didn't account for the fact that GitHub pretends missing repos are private and asks for authentication.  Therefore we'd block at a password prompt:
Username for 'https://github.com':
Disable password prompting during this fetch so the fallback can run.
Fixes #13.  Fixes …
=> tmpl8: fix cache sync for repos that haven't been forked

.github/workflows/check.yml, .github/workflows/sync.yml
tmpl8 isn't in the root of the repo, so its `target/` directory isn't either.  Configure rust-cache to look in the right place for dependencies to cache.
=> workflows: correctly configure tmpl8 workspace path for caching

config.yaml, rust/release-checklist.md, rust/release-checklist.yaml
We always ship vendor tarballs for Rust applications and never ship them for Rust libraries.  Add a `library_crate` flag, for future broader use, and switch the conditionals over to use it.
No output change intended.
=> rust: replace `do_vendor_tarball` with top-level `library_crate` flag

rust/tests.yml
By default, `cargo test` builds examples but does not test them (if any test cases exist) and `cargo clippy` does not check tests or examples. Run both with `--all-targets` to fix this.
Also run `cargo build` with `--all-targets`, since it's clearer if examples are built during the build phase rather than the test phase.
=> rust: run build/test/clippy with `--all-targets`

rust/tests.yaml
There are no new lints in any of the projects, and the false positive in bootupd has been fixed.
=> rust: bump clippy to 1.70.0

fcos/release-checklist.md
We are now releasing for ppc64le so let's add steps to our checklist for it.
=> release-checklist: add steps for ppc64le architecture

fcos/release-checklist.md
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1377
=> release-checklist: check aarch64 GCP runs

fcos/release-checklist.md
Update the formatting for the kola azure and kola gcp runs to match the rest of the kola runs. This will also make it clear which arches to check for on kola azure.
=> release-checklist: update sanity check formatting

go/signing-ticket.sh
The bottom of the signing ticket has an example list of output files, but the list isn't in the order produced by `ls` because it's sorted by map keys, not values.  Sort by value to fix that.
=> go: sort filenames in list of signing outputs

rust/release-checklist.md
Sometimes a Dependabot update will needlessly increase the minimum supported version of a dependency, and PR review won't catch it.  Add an additional check before starting a release.
=> rust: check `Cargo.toml` for unintended increases of lower version bounds

rust/release-checklist.md
Forgot to use `-a` when amending.
=> rust: checklist wording improvement

docs/_config.yml
See: https://github.com/just-the-docs/just-the-docs/releases/tag/v0.6.0
=> docs: Update just-the-docs theme to 0.6.0

dependabot/dependabot.yaml
Some projects written in Rust do not need frequent dependency updates, thus move to a monthly dependency schedule.
=> dependabot: Use a monthly schedule for some Rust projects

config.yaml
Related to this https://github.com/coreos/ignition/pull/1733
=> config.yaml: remove EOL go_versions 

go/release-checklist.md, rust/release-checklist.md
We had an instance recently where we thought the release was done, but the ART ticket was blocked on more information and we didn't notice until much later when users started wondering where the new version was.
Let's hard require the ART ticket to be closed before we can close the release ticket.
=> release-checklist: wait until mirror.openshift.com is updated

go/tests.yaml
Found that the older version of golangci_lint was resulting in failing tests for go 1.21. With the latest version this seems to be resolved.
=> Update golangci_lint to 1.55.1

go/tests.yaml
As of golang 1.23 the golangci-linter needs to be updated to 1.60.1 See that here: https://github.com/golangci/golangci-lint/releases
=> test: update golangci-linter to latest

.github/dependabot.yml, dependabot/dependabot.yml
Inspired by https://github.com/coreos/bootupd/pull/758#issuecomment-2441048372
=> dependabot: add "github-actions"

container/container-rebuild.yml, container/container.yml, go/tests-ignition.yml, go/tests.yml, rust/rpm-test.yml, rust/tests.yml, shellcheck/workflow.yml
- Update actions/checkout to v4
- Update actions/upload-artifact to v4
=> *: Update GitHub Actions tags

rust/rpm-test.yml
Builds are failing on Ubuntu 24.04 due to a bug in mock/usermode [1].
Revert back to Ubuntu 22.04 for now, likely until we move to Packit for building test RPMs.
[1] https://github.com/coreos/afterburn/issues/1156
See: https://github.com/coreos/coreos-installer/issues/1589
See: https://github.com/coreos/afterburn/issues/1156
=> rust/rpm-test: Run on Ubuntu 22.04 for now

fcos/release-checklist.md
The default has changed for EARLY_ARCH_JOBS to false[0]. Update the release checklist to enable EARLY_ARCH_JOBS to match the previous process for quicker builds.
[0] https://github.com/coreos/fedora-coreos-pipeline/pull/1085
Depends on  https://github.com/coreos/fedora-coreos-pipeline/pull/1085
=> fcos/release.md: enable EARLY_ARCH_JOBS

rust/tests.yml
These changes were made downstream in https://github.com/coreos/zincati/commit/5b79f1559a38a4ae3c2197adf0b28ca9ac08cac0 so let's add the changes here to sync downstream instead.
"in https://github.com/coreos/zincati/commit/32d76f6a678228a4aa8239f08fec2a61cc588258 we added ostree bindings to parse image references, which in turn require glib-devel dependencies to build.
Let's use the fcos-buildroot container to run the CI so we have to maintain the correct set of dependencies in one place."
=> rust/tests: use fcos-buildroot container to lint rust

config.yaml, go/tests.yaml
go 1.22 is no longer in support.
=> go: update go_versions to 1.23 and 1.24 and linter to 1.64.4

rust/tests.yaml
Afterburn build is failing due to dependancy's which are waiting on lint_toolchain to be 1.84.1. Update 1.84.1 to fix CI for downstream repos.
See: https://github.com/coreos/afterburn/actions/runs/13607099114/job/38039854721?pr=1171
=> tests: update rust lint_toolchain 1.84.1

rust/release-checklist.md
Packit submits the PR after a new version is released upstream, so we can remove those steps.
=> rust/checklist: update fedora packaging section

fcos/release-checklist.md
We are now running the kola-azure job with both x86_64 and aarch64 images. Add a check to verify the new aarch64 run has passed.
xref: https://github.com/coreos/fedora-coreos-pipeline/pull/1162
=> fcos/release-checklist.md: add check for kola-azure-aarch64

go/tests.yaml
Fixes the golangci-lint version used in the CI workflow to a supported version, resolving compatibility errors with golangci-lint-action@v8.
=> fix: Update golangci-lint version

gemini/config.yaml
The config file needs to be .yaml to be read by the gemini app.
=> Gemini config file needs to be .yaml and not .yml

rust/release-checklist.md
We want the `/pull-requests` to be part of the URL/link created by markdown when rendered.
=> rust/release-checklist: fix typo in markdown URL

dependabot/dependabot.yml
This reduces some noise if tests pass and allows us to do less click maintenance. It seems to be working well for COSA: https://github.com/coreos/coreos-assembler/pull/4188
If we end up in a situation where one update in the bunch is problematic we can interact through comments with dependabot and kick it out of the update into its own PR.
=> dependabot: group updates in a single PR

go/tests.yml
This PR separates the `gofmt` check from the main `golangci-lint `step.
This is necessary because the `golangci-lint-action` is hardcoded to use the `run` command and cannot be instructed to use `fmt`, making it unsuitable for formatting-only checks after the `golangci-lint `v2 update.
The new step provides clearer feedback by `gofmt -d` in the CI logs. The main linter is updated to exclude `gofmt` to prevent redundant work.
This is also related to the migration from golangci-lint `v1` to `v2` where the `gofmt `is used changed. You can check more about it here: https://golangci-lint.run/product/migration-guide/
=> CI: Separate gofmt check from linting step

go/tests.yml
On windows the different handling of line endings can cause gofmt to fail.
Fixes 641cbf5
=> go/tests: only check gofmt on Linux
